Replace Logger declarations
celements/celements-xwiki pull request #149
Opened 2021-06-11 17:07 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-454

2021-06-14 10:28 UTC, fpichler requested changes

2021-06-14 10:28 UTC, fpichler commented on celements-model/src/main/java/com/celements/filebase/AttachmentService.java
> +  private static Logger LOGGER = LoggerFactory.getLogger(AttachmentService.class);
```suggestion
  private static final Logger LOGGER = LoggerFactory.getLogger(AttachmentService.class);
```

2021-06-14 10:28 UTC, fpichler commented on LoadTesting/src/main/java/com/celements/web/utils/DocumentCreationWorker.java
>        } catch (XWikiException e) {
```suggestion
      } catch (XWikiException | NullPointerException exp) {
```

2021-06-14 10:28 UTC, fpichler commented on LoadTesting/src/main/java/com/celements/web/utils/DocumentCreationWorker.java
> +        LOGGER.error(context.getWiki() + " - " + docFullName, e);
```suggestion
        LOGGER.error("{} - {}", context.getWiki(), docFullName, exp);
```

2021-06-14 10:28 UTC, fpichler commented on LoadTesting/src/main/java/com/celements/web/utils/DocumentCreationWorker.java
>        } catch (NullPointerException npe) {
```suggestion
```

2021-06-14 10:28 UTC, fpichler commented on LoadTesting/src/main/java/com/celements/web/utils/DocumentCreationWorker.java
> +        LOGGER.error(context.getWiki() + " - " + docFullName, npe);
```suggestion
```

2021-06-14 13:28 UTC, msladek commented
@fpichler please note that I only performed workspace wide search&replace operations. it isn't the original intention of these PRs to refactor anything else except the logger declarations and definitons.

2021-06-16 04:43 UTC, fpichler approved these changes

2021-06-16 09:17 UTC, merged