Immutable references
celements/celements-xwiki pull request #167
Opened 2022-02-08 15:26 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-1010

2022-02-08 15:56 UTC, fpichler requested changes

2022-02-08 15:56 UTC, fpichler commented on celements-reference/src/main/java/org/xwiki/model/internal/DefaultModelConfiguration.java
> +  private final Logger logger = LoggerFactory.getLogger(this.getClass());
please make logger static -> naming: capital letters

2022-02-14 04:32 UTC, fpichler requested changes

2022-02-14 04:32 UTC, fpichler commented on celements-reference/src/main/java/org/xwiki/model/reference/DocumentReference.java
>  public class DocumentReference extends EntityReference {
please add a static final serialVersionUID of type long (part of the Serializable contract)

2022-02-14 04:32 UTC, fpichler commented on celements-reference/src/main/java/org/xwiki/model/reference/EntityReference.java
> +        parameters = new TreeMap<>();
TreeMap is not thread safe. Thus calling setParameter outside of the constructor leads to not thread safe objects. I could not find any calls outside of custructors. Yet, maybe explain in JavaDoc or just change TreeMap to ConcurrentSkipListMap

2022-02-20 22:50 UTC, msladek commented on celements-reference/src/main/java/org/xwiki/model/reference/EntityReference.java
> +        parameters = new TreeMap<>();
Strangely XWiki hasn't implemented immutability with final fields but with protected setter methods called in the constructor which are overwritten by subclasses. I don't know the reason for this design choice. I have refactored the `TreeMap` to a `final ImmutableMap` and removed the `setParameter` method.

2022-02-21 11:59 UTC, fpichler requested changes

2022-02-21 11:59 UTC, fpichler commented on celements-reference/src/main/java/org/xwiki/model/reference/DocumentReference.java
>   * Represents a reference to a document (wiki, space and page names).
"(wiki, space and page names)" maybe "language" or Local should be added to this java comment, wdyt?

2022-02-21 15:54 UTC, fpichler approved these changes

2022-02-22 12:10 UTC, merged