DanglingPropertiesMigration
celements/celements-xwiki pull request #31
Opened 2018-04-15 15:00 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-657

2018-04-15 15:13 UTC, msladek commented on celements-model/src/main/java/com/celements/query/CelMySQLDialect.java
> +public class CelMySQLDialect extends MySQLDialect {
see [this comment](https://synjira.atlassian.net/browse/CELDEV-657?focusedCommentId=32770&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-32770) for more information

2018-04-15 15:36 UTC, fpichler requested changes

2018-04-15 15:36 UTC, fpichler commented on celements-model/src/main/java/com/celements/model/migration/DanglingPropertiesMigration.java
> +    LOGGER.info("[{}] dangling properties:", table);
please either log dangling data on warning level (because it gets deleted) or write the data to a special dangling-properties table.

2018-04-15 22:50 UTC, fpichler approved these changes

2018-04-16 15:23 UTC, ebeutler approved these changes

2018-04-17 06:02 UTC, merged