fix generatePrettyName for non alphanumeric
celements/celements-xwiki pull request #79
Opened 2018-11-28 16:30 UTC by msladek

2018-12-03 12:13 UTC, fpichler requested changes
Add PR description with link issue

2018-12-04 01:22 UTC, msladek commented
added PR description and added some things. please re-review

2018-12-04 05:24 UTC, fpichler requested changes

2018-12-04 05:24 UTC, fpichler commented on celements-model/src/main/java/com/celements/model/field/XObjectFieldAccessor.java
> +    if (field.getClassDef() == xObjClassDef) {
Isn't it better to use **equals**? Even though classdefinition should be a singleton.

2018-12-04 10:26 UTC, msladek commented on celements-model/src/main/java/com/celements/model/field/XObjectFieldAccessor.java
> +    if (field.getClassDef() == xObjClassDef) {
yes it would be more robust. ClassDefs can also be looked up via package interface, though this should only happen within the package. I've changed this.

2018-12-04 18:52 UTC, fpichler approved these changes

2018-12-04 23:01 UTC, merged